ERROR app.py:1744 Exception on /play/searchMovies [GET]
Traceback (most recent call last):
  File "C:\Users\grade\Desktop\openai-quickstart-python-master\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\grade\Desktop\openai-quickstart-python-master\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\grade\Desktop\openai-quickstart-python-master\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\grade\Desktop\openai-quickstart-python-master\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\grade\Desktop\openai-quickstart-python-master\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\grade\Desktop\openai-quickstart-python-master\chat\bluePrints\playBluePrint.py", line 70, in searchMovies
    page_size = re.findall(r'\d+', last_page_url)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\re.py", line 241, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or bytes-like object
ERROR app.py:1744 Exception on /play/searchMovies [GET]
Traceback (most recent call last):
  File "C:\Users\grade\Desktop\openai-quickstart-python-master\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\grade\Desktop\openai-quickstart-python-master\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\grade\Desktop\openai-quickstart-python-master\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\grade\Desktop\openai-quickstart-python-master\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\grade\Desktop\openai-quickstart-python-master\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\grade\Desktop\openai-quickstart-python-master\chat\bluePrints\playBluePrint.py", line 74, in searchMovies
    for current_page in range(page_size):
TypeError: 'str' object cannot be interpreted as an integer
ERROR app.py:1744 Exception on /play/searchMovies [GET]
Traceback (most recent call last):
  File "C:\Users\grade\Desktop\openai-quickstart-python-master\venv\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\grade\Desktop\openai-quickstart-python-master\venv\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\grade\Desktop\openai-quickstart-python-master\venv\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\grade\Desktop\openai-quickstart-python-master\venv\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\grade\Desktop\openai-quickstart-python-master\venv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\grade\Desktop\openai-quickstart-python-master\chat\bluePrints\playBluePrint.py", line 56, in searchMovies
    result_list += page_result
TypeError: 'Response' object is not iterable
